/**
 * Scenario runner backed by the WasmEngine (reebe-wasm).
 *
 * Works in both browser and Node.js:
 *   - Browser: WASM is loaded via the default export (fetch-based).
 *   - Node.js:  WASM bytes are read from disk via initSync to avoid
 *               Node's lack of fetch() support for file:// URLs.
 *
 * Creates a fresh WasmEngine per scenario for clean isolation, deploys the
 * current BPMN XML (and all referenced DMN/BPMN resources recursively), drives
 * jobs to completion using mock outputs from the scenario definition, then
 * asserts expectations.
 */

// ── Snapshot types (mirrors wasm-adapter shape) ───────────────────────────────

interface WasmProcessInstance {
	key: number
	bpmn_process_id: string
	state: string
}

interface WasmJob {
	key: number
	job_type: string
	state: string
	process_instance_key: number
	element_id: string
}

interface WasmElementInstance {
	key: number
	process_instance_key: number
	element_id: string
	state: string
}

interface WasmVariable {
	name: string
	value: unknown
	process_instance_key: number
}

interface WasmIncident {
	process_instance_key: number
	element_id: string
	error_type: string
	error_message: string | null
}

interface WasmSnapshot {
	processInstances: WasmProcessInstance[]
	elementInstances: WasmElementInstance[]
	jobs: WasmJob[]
	variables: WasmVariable[]
	incidents: WasmIncident[]
}

interface DeployResponse {
	deployments: Array<{ bpmnProcessId: string }>
}

interface WasmEngineInstance {
	deploy(xml: string): unknown
	create_process_instance(processId: string, variables: string): void
	activate_job(key: number, worker: string, timeout: number): void
	complete_job(key: number, variables: string): void
	fail_job(key: number, retries: number, message: string): void
	snapshot(): unknown
	free(): void
}

// ── Scenario types ────────────────────────────────────────────────────────────

export interface ScenarioLike {
	id: string
	name: string
	processId?: string
	inputs?: Record<string, unknown>
	mocks?: Record<string, { outputs?: Record<string, unknown>; error?: string }>
	expect?: {
		path?: string[]
		variables?: Record<string, unknown>
	}
}

export interface ScenarioResultLike {
	scenarioId: string
	scenarioName: string
	passed: boolean
	visitedElements: string[]
	finalVariables: Record<string, unknown>
	errors: Array<{ elementId?: string; message: string }>
	failures: Array<{ field: string; expected: unknown; actual: unknown }>
	durationMs: number
}

// ── WASM initialisation ───────────────────────────────────────────────────────

let wasmReady = false

async function ensureWasmInit(): Promise<void> {
	if (wasmReady) return
	const mod = await import("@bpmnkit/reebe-wasm")
	// Node.js: fetch() does not support file:// URLs generated by wasm-bindgen,
	// so we read the .wasm bytes from disk and use initSync.
	if (typeof process !== "undefined" && typeof process.versions?.node === "string") {
		const { readFileSync } = await import("node:fs")
		const { createRequire } = await import("node:module")
		const { dirname, resolve } = await import("node:path")
		const req = createRequire(import.meta.url)
		const jsPath: string = req.resolve("@bpmnkit/reebe-wasm")
		const wasmPath = resolve(dirname(jsPath), "reebe_wasm_bg.wasm")
		mod.initSync({ module: readFileSync(wasmPath) })
	} else {
		await mod.default()
	}
	wasmReady = true
}

// ── Recursive dependency deployment ──────────────────────────────────────────

function deployDependencies(
	xml: string,
	engine: WasmEngineInstance,
	getDecisionDmn: ((id: string) => string | null) | undefined,
	getProcessBpmn: ((id: string) => string | null) | undefined,
	deployed: Set<string>,
): string[] {
	const missingDecisions: string[] = []

	// DMN decisions referenced via decisionId="..."
	if (getDecisionDmn) {
		for (const [, id] of xml.matchAll(/decisionId="([^"]+)"/g)) {
			if (!id || deployed.has(`dmn:${id}`)) continue
			deployed.add(`dmn:${id}`)
			const dmnXml = getDecisionDmn(id)
			if (dmnXml) {
				try {
					engine.deploy(dmnXml)
				} catch {
					missingDecisions.push(id)
				}
			} else {
				missingDecisions.push(id)
			}
		}
	}

	// Sub-processes / call activities referenced via calledElement="..."
	if (getProcessBpmn) {
		for (const [, id] of xml.matchAll(/calledElement="([^"]+)"/g)) {
			if (!id || deployed.has(`bpmn:${id}`)) continue
			deployed.add(`bpmn:${id}`)
			const bpmnXml = getProcessBpmn(id)
			if (bpmnXml) {
				const nested = deployDependencies(bpmnXml, engine, getDecisionDmn, getProcessBpmn, deployed)
				missingDecisions.push(...nested)
				engine.deploy(bpmnXml)
			}
		}
	}

	return missingDecisions
}

// ── Runner ────────────────────────────────────────────────────────────────────

const MAX_ROUNDS = 200
const TIMEOUT_MS = 10_000

export async function runScenarioWasm(
	xml: string,
	scenario: ScenarioLike,
	getDecisionDmn?: (decisionId: string) => string | null,
	getProcessBpmn?: (processId: string) => string | null,
): Promise<ScenarioResultLike> {
	const startMs = Date.now()

	await ensureWasmInit()
	const mod = await import("@bpmnkit/reebe-wasm")
	const engine = new mod.WasmEngine() as WasmEngineInstance

	try {
		const deployed = new Set<string>()
		const missingDecisions = deployDependencies(
			xml,
			engine,
			getDecisionDmn,
			getProcessBpmn,
			deployed,
		)

		// Deploy main BPMN
		const deployResult = engine.deploy(xml) as DeployResponse
		const processId = scenario.processId ?? deployResult.deployments[0]?.bpmnProcessId
		if (!processId) {
			return fail(scenario, startMs, "No process found in deployed BPMN.")
		}

		// Start instance
		engine.create_process_instance(processId, JSON.stringify(scenario.inputs ?? {}))

		// Drive jobs to completion
		for (let round = 0; round < MAX_ROUNDS; round++) {
			if (Date.now() - startMs > TIMEOUT_MS) break

			const snap = engine.snapshot() as WasmSnapshot
			const pi = snap.processInstances.find((p) => p.bpmn_process_id === processId)

			if (!pi || pi.state !== "ACTIVE") break

			const activatable = snap.jobs.filter(
				(j) => j.state === "ACTIVATABLE" && j.process_instance_key === pi.key,
			)
			if (activatable.length === 0) break

			for (const job of activatable) {
				try {
					engine.activate_job(job.key, "test-worker", 30_000)
					const mock = scenario.mocks?.[job.job_type]
					if (mock?.error !== undefined) {
						engine.fail_job(job.key, 0, mock.error)
					} else {
						engine.complete_job(job.key, JSON.stringify(mock?.outputs ?? {}))
					}
				} catch {
					// Job may have already been handled — skip
				}
			}
		}

		// Collect final state
		const snap = engine.snapshot() as WasmSnapshot
		const pi = snap.processInstances.find((p) => p.bpmn_process_id === processId)

		if (!pi) return fail(scenario, startMs, "Process instance not found after run.")

		const timedOut = pi.state === "ACTIVE" && Date.now() - startMs >= TIMEOUT_MS

		const visitedElements = snap.elementInstances
			.filter((e) => e.process_instance_key === pi.key)
			.map((e) => e.element_id)

		const finalVariables: Record<string, unknown> = {}
		for (const v of snap.variables.filter((v) => v.process_instance_key === pi.key)) {
			finalVariables[v.name] = v.value
		}

		const errors: ScenarioResultLike["errors"] = snap.incidents
			.filter((i) => i.process_instance_key === pi.key)
			.map((i) => ({ elementId: i.element_id, message: i.error_message ?? i.error_type }))

		for (const id of missingDecisions) {
			errors.push({ message: `DMN decision '${id}' not found. Create the DMN in the Models view.` })
		}

		if (timedOut) {
			errors.push({ message: `Scenario timed out after ${TIMEOUT_MS}ms` })
		}

		// Evaluate assertions
		const failures: ScenarioResultLike["failures"] = []

		if (scenario.expect?.path !== undefined) {
			let cursor = 0
			for (const expectedId of scenario.expect.path) {
				const idx = visitedElements.indexOf(expectedId, cursor)
				if (idx === -1) {
					failures.push({
						field: "path",
						expected: expectedId,
						actual: `not found in [${visitedElements.join(", ")}]`,
					})
				} else {
					cursor = idx + 1
				}
			}
		}

		if (scenario.expect?.variables !== undefined) {
			for (const [key, expectedValue] of Object.entries(scenario.expect.variables)) {
				const actualValue = finalVariables[key]
				if (JSON.stringify(actualValue) !== JSON.stringify(expectedValue)) {
					failures.push({ field: `variables.${key}`, expected: expectedValue, actual: actualValue })
				}
			}
		}

		return {
			scenarioId: scenario.id,
			scenarioName: scenario.name,
			passed: failures.length === 0,
			visitedElements,
			finalVariables,
			errors,
			failures,
			durationMs: Date.now() - startMs,
		}
	} finally {
		engine.free()
	}
}

function fail(scenario: ScenarioLike, startMs: number, message: string): ScenarioResultLike {
	return {
		scenarioId: scenario.id,
		scenarioName: scenario.name,
		passed: false,
		visitedElements: [],
		finalVariables: {},
		errors: [{ message }],
		failures: [{ field: "start", expected: "process to deploy and start", actual: message }],
		durationMs: Date.now() - startMs,
	}
}
