/**
 * Official Camunda REST Outbound Connector element template.
 * Source: https://github.com/camunda/connectors/tree/main/connectors/http/rest
 * Version: 12  —  Requires Camunda 8.3+
 */
import type { ElementTemplate } from "../template-types.js";

export const REST_CONNECTOR_TEMPLATE: ElementTemplate = {
	id: "io.camunda.connectors.HttpJson.v2",
	name: "REST Outbound Connector",
	description: "Invoke REST API",
	version: 12,
	appliesTo: ["bpmn:Task"],
	elementType: { value: "bpmn:ServiceTask" },
	documentationRef: "https://docs.camunda.io/docs/components/connectors/protocol/rest/",
	groups: [
		{ id: "authentication", label: "Authentication" },
		{ id: "endpoint", label: "HTTP endpoint" },
		{ id: "timeout", label: "Connection timeout" },
		{ id: "payload", label: "Payload" },
		{ id: "output", label: "Output mapping" },
		{ id: "error", label: "Error handling" },
		{ id: "retries", label: "Retries" },
	],
	properties: [
		// ── Task type (hidden, fixed) ────────────────────────────────────────────
		{
			value: "io.camunda:http-json:1",
			binding: { type: "zeebe:taskDefinition", property: "type" },
			type: "Hidden",
		},
		// ── Authentication ───────────────────────────────────────────────────────
		{
			id: "authentication.type",
			label: "Type",
			description:
				"Choose the authentication type. Select 'None' if no authentication is necessary.",
			value: "noAuth",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.type" },
			type: "Dropdown",
			choices: [
				{ name: "API key", value: "apiKey" },
				{ name: "Basic", value: "basic" },
				{ name: "Bearer token", value: "bearer" },
				{ name: "None", value: "noAuth" },
				{ name: "OAuth 2.0", value: "oauth-client-credentials-flow" },
			],
		},
		// API key
		{
			id: "authentication.apiKeyLocation",
			label: "API key location",
			description: "Send API key in header or as query parameter.",
			value: "headers",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.apiKeyLocation" },
			condition: { property: "authentication.type", equals: "apiKey" },
			type: "Dropdown",
			choices: [
				{ name: "Headers", value: "headers" },
				{ name: "Query parameters", value: "query" },
			],
		},
		{
			id: "authentication.name",
			label: "API key name",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.name" },
			condition: { property: "authentication.type", equals: "apiKey" },
			type: "String",
		},
		{
			id: "authentication.value",
			label: "API key value",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.value" },
			condition: { property: "authentication.type", equals: "apiKey" },
			type: "String",
		},
		// Basic auth
		{
			id: "authentication.username",
			label: "Username",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.username" },
			condition: { property: "authentication.type", equals: "basic" },
			type: "String",
		},
		{
			id: "authentication.password",
			label: "Password",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.password" },
			condition: { property: "authentication.type", equals: "basic" },
			type: "String",
		},
		// Bearer token
		{
			id: "authentication.token",
			label: "Bearer token",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.token" },
			condition: { property: "authentication.type", equals: "bearer" },
			type: "String",
		},
		// OAuth 2.0
		{
			id: "authentication.oauthTokenEndpoint",
			label: "OAuth 2.0 token endpoint",
			description: "The OAuth token endpoint",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.oauthTokenEndpoint" },
			condition: { property: "authentication.type", equals: "oauth-client-credentials-flow" },
			type: "String",
		},
		{
			id: "authentication.clientId",
			label: "Client ID",
			description: "Your application's client ID from the OAuth client",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.clientId" },
			condition: { property: "authentication.type", equals: "oauth-client-credentials-flow" },
			type: "String",
		},
		{
			id: "authentication.clientSecret",
			label: "Client secret",
			description: "Your application's client secret from the OAuth client",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.clientSecret" },
			condition: { property: "authentication.type", equals: "oauth-client-credentials-flow" },
			type: "String",
		},
		{
			id: "authentication.audience",
			label: "Audience",
			description: "The unique identifier of the target API you want to access",
			optional: true,
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.audience" },
			condition: { property: "authentication.type", equals: "oauth-client-credentials-flow" },
			type: "String",
		},
		{
			id: "authentication.clientAuthentication",
			label: "Client authentication",
			description: "Send client credentials in the request body or as Basic Auth header",
			value: "credentialsBody",
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.clientAuthentication" },
			condition: { property: "authentication.type", equals: "oauth-client-credentials-flow" },
			type: "Dropdown",
			choices: [
				{ name: "Send client credentials in body", value: "credentialsBody" },
				{ name: "Send as Basic Auth header", value: "basicAuthHeader" },
			],
		},
		{
			id: "authentication.scopes",
			label: "Scopes",
			description: "Scopes to request authorization for (e.g. read:contacts)",
			optional: true,
			group: "authentication",
			binding: { type: "zeebe:input", name: "authentication.scopes" },
			condition: { property: "authentication.type", equals: "oauth-client-credentials-flow" },
			type: "String",
		},
		// ── Endpoint ─────────────────────────────────────────────────────────────
		{
			id: "method",
			label: "Method",
			value: "GET",
			group: "endpoint",
			binding: { type: "zeebe:input", name: "method" },
			type: "Dropdown",
			choices: [
				{ name: "GET", value: "GET" },
				{ name: "POST", value: "POST" },
				{ name: "PUT", value: "PUT" },
				{ name: "PATCH", value: "PATCH" },
				{ name: "DELETE", value: "DELETE" },
			],
		},
		{
			id: "url",
			label: "URL",
			group: "endpoint",
			binding: { type: "zeebe:input", name: "url" },
			type: "String",
		},
		{
			id: "headers",
			label: "Headers",
			description: "Map of HTTP headers to add to the request",
			optional: true,
			feel: "required",
			group: "endpoint",
			binding: { type: "zeebe:input", name: "headers" },
			type: "String",
			placeholder: '= { "Content-Type": "application/json" }',
		},
		{
			id: "queryParameters",
			label: "Query parameters",
			description: "Map of query parameters to add to the request URL",
			optional: true,
			feel: "required",
			group: "endpoint",
			binding: { type: "zeebe:input", name: "queryParameters" },
			type: "String",
			placeholder: '= { "page": 1, "limit": 10 }',
		},
		// ── Timeout ──────────────────────────────────────────────────────────────
		{
			id: "connectionTimeoutInSeconds",
			label: "Connection timeout (seconds)",
			description: "Connection timeout in seconds, or 0 for infinite",
			value: 20,
			group: "timeout",
			binding: { type: "zeebe:input", name: "connectionTimeoutInSeconds" },
			type: "Number",
		},
		{
			id: "readTimeoutInSeconds",
			label: "Read timeout (seconds)",
			description: "Read timeout in seconds, or 0 for infinite",
			value: 20,
			group: "timeout",
			binding: { type: "zeebe:input", name: "readTimeoutInSeconds" },
			type: "Number",
		},
		// ── Payload ──────────────────────────────────────────────────────────────
		{
			id: "body",
			label: "Request body",
			description: "Payload to send with the request",
			optional: true,
			feel: "optional",
			group: "payload",
			binding: { type: "zeebe:input", name: "body" },
			condition: { property: "method", oneOf: ["POST", "PUT", "PATCH"] },
			type: "Text",
			placeholder: '= { "orderId": orderId }',
		},
		// ── Output mapping ───────────────────────────────────────────────────────
		{
			id: "resultVariable",
			label: "Result variable",
			description: "Process variable to store the full response in",
			optional: true,
			group: "output",
			binding: { type: "zeebe:taskHeader", key: "resultVariable" },
			type: "String",
			placeholder: "response",
		},
		{
			id: "resultExpression",
			label: "Result expression",
			description: "FEEL expression to extract values from the response into process variables",
			optional: true,
			feel: "required",
			group: "output",
			binding: { type: "zeebe:taskHeader", key: "resultExpression" },
			type: "Text",
			placeholder: "= { orderId: response.body.id }",
		},
		// ── Error handling ───────────────────────────────────────────────────────
		{
			id: "errorExpression",
			label: "Error expression",
			description: "FEEL expression to handle errors",
			optional: true,
			feel: "required",
			group: "error",
			binding: { type: "zeebe:taskHeader", key: "errorExpression" },
			type: "Text",
		},
		// ── Retries ──────────────────────────────────────────────────────────────
		{
			id: "retryCount",
			label: "Retries",
			description: "Number of retries on failure",
			value: "3",
			group: "retries",
			binding: { type: "zeebe:taskDefinition", property: "retries" },
			type: "String",
		},
		{
			id: "retryBackoff",
			label: "Retry backoff",
			description: "ISO 8601 duration to wait between retries (e.g. PT5S for 5 seconds)",
			value: "PT0S",
			group: "retries",
			binding: { type: "zeebe:taskHeader", key: "retryBackoff" },
			type: "String",
		},
	],
};
