import type { BpmnDefinitions } from "../bpmn-model.js"

export type OptimizationSeverity = "info" | "warning" | "error"
export type OptimizationCategory =
	| "feel"
	| "flow"
	| "naming"
	| "task-reuse"
	| "extract"
	| "pattern"
	| "data-flow"

export interface ApplyFixResult {
	description: string
	/** New BpmnDefinitions generated by the fix (e.g. extracted reusable sub-process). */
	generated?: BpmnDefinitions
}

export interface OptimizationFinding {
	id: string
	category: OptimizationCategory
	severity: OptimizationSeverity
	message: string
	suggestion: string
	processId: string
	elementIds: string[]
	/** Mutates `defs` in-place. Returns what changed + any generated file. */
	applyFix?: (defs: BpmnDefinitions) => ApplyFixResult
	/** Data-flow: variable names produced (written) by the associated element. */
	produces?: string[]
	/** Data-flow: variable names consumed (read) by the associated element. */
	consumes?: string[]
}

export interface OptimizationReport {
	findings: OptimizationFinding[]
	summary: {
		total: number
		byCategory: Record<OptimizationCategory, number>
		bySeverity: Record<OptimizationSeverity, number>
	}
}

export interface OptimizeOptions {
	feelLengthThreshold?: number
	feelNestingThreshold?: number
	feelOperatorThreshold?: number
	feelVariableThreshold?: number
	reuseThreshold?: number
	categories?: OptimizationCategory[]
}

export interface ResolvedOptions {
	feelLengthThreshold: number
	feelNestingThreshold: number
	feelOperatorThreshold: number
	feelVariableThreshold: number
	reuseThreshold: number
	categories: OptimizationCategory[]
}
